import React, {ReactNode} from "react";
import type { Metadata } from 'next'

// These styles apply to every route in the application
import './globals.css'

export const metadata: Metadata = {
    title: 'Webeaver',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <link rel="icon" href="/logo.png"/>
        <body>{children}</body>
        </html>
    )
}